### ISSUE TITLE
Make returned object dimensions consistent in get_clean_obs

### ISSUE THREAD

**Issue by jcoliver** [keatonwilson/insect_migration#2]
When there are fewer than 10K records, the returned data has 6 columns, but when the number is > 10K, the `key` column is not returned. Either remove `key` column from resulting data when there are fewer than 10K records (via `select()` ?) or allow it to persist for results with > 10K records.

**Comment by keatonwilson** [comment]
Removed key via `select()` function in < 10k records. Will commit and push in a bit.
