### ISSUE TITLE
Combining GBIF and iNat records needs check for 0 results in get_clean_obs

### ISSUE THREAD

**Issue by jcoliver** [keatonwilson/insect_migration#3]
In the case of >10K records, need a check to ensure `inat_df` and `gbif_df` have >= 1 rows of post-filtering; if either has 0 rows, calling `factor()` in `mutate()` will fail due to differing vector lengths. i.e. if there are 0 records in the `gbif_df`, the number of unique values in the `prov` column will be less than the number of values in the vector provided to `labels` argument.

**Comment by keatonwilson** [comment]
Changed it to output to character ("gbif" or "inat"), then did a second step mutating to factor. This is after combining, so factor() should encompass scenarios with solely inat or gbif correctly. Will commit and push in a second.
